name: Destroy Terraform Module

on:
  workflow_dispatch:
    inputs:
      module_name:
        description: 'Enter the module name to destroy (e.g., IAM, EC2, S3)'
        required: true
      confirm_destroy:
        description: 'Type "YES" to confirm destruction'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy-module:
    runs-on: ubuntu-latest

    steps:
      - name: Check confirmation
        if: github.event.inputs.confirm_destroy != 'YES'
        run: echo "Destruction not confirmed. Exiting." && exit 1

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: Terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: Terraform

      - name: Terraform Plan (Destroy Specific Module)
        run: terraform plan -destroy -target=module.${{ github.event.inputs.module_name }}
        working-directory: Terraform

      - name: Terraform Destroy (Selected Module)
        run: terraform destroy -auto-approve -target=module.${{ github.event.inputs.module_name }}
        working-directory: Terraform
