name: Deploy Terraform

on:
  push:
    branches:
      - main
    paths:
      - 'Terraform/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: Terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: Terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: Terraform

      - name: Remove IAM User from Terraform State (if needed)
        run: terraform state rm aws_iam_user.my_user || true
        working-directory: Terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: Terraform
